kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: tests
    image: python:3.7
    commands:
      - pip install pipenv
      - pipenv install --dev --ignore-pipfile
      - pipenv run pytest

  - name: docker
    image: plugins/docker
    environment:
      STEAM_USERNAME:
        from_secret: STEAM_USERNAME
      STEAM_PASSWORD:
        from_secret: STEAM_PASSWORD
    settings: 
      username: 
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: phoenixza/zags
      tags: latest
      build_args:
        - STEAM_USERNAME=$STEAM_USERNAME
        - STEAM_PASSWORD=$STEAM_PASSWORD
    when:
      branch:
        - master
  
  - name: notify
    image: appleboy/drone-discord
    settings: 
      webhook_id: 
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
