sudo: enabled
services:
  - docker
language: generic
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
install:
  - pip3 install pipenv
  - pipenv install --dev --ignore-pipfile
script:
  - pipenv run python pytest
deploy:
  provider: script
  script: python scripts/docker_push.py
  on:
    branch: master
