sudo: enabled
services:
  - docker
language: generic
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.7
before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3.7 get-pip.py
  - rm get-pip.py
  - pip install pipenv
install: pipenv install --dev --ignore-pipfile
script:
  - pipenv run python pytest
deploy:
  provider: script
  script: python scripts/docker_push.py
  on:
    branch: master
