sudo: enabled
services:
  - docker
language: python
python:
  - "3.7-dev"
install:
  - pip install pipenv
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install --dev --ignore-pipfile
script:
  - pipenv run python pytest
deploy:
  provider: script
  script: python scripts/docker_push.py
  on:
    branch: master
