sudo: enabled
services:
  - docker
language: python
python:
  - "3.7-dev"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python pytest
deploy:
  provider: script
  script: python scripts/docker_push.py
  on:
    branch: master
